import { env } from "cloudflare:workers";
import { getMigrations } from "better-auth/db/migration";
import { describe, expect, it } from "vitest";

import { createAuth } from "../src/auth/create-auth";

const NOW = 1_787_000_000_000;

async function insertUser(userId: string, email: string): Promise<void> {
  await env.DB.prepare(
    `INSERT INTO "user" (
      "id", "name", "email", "emailVerified", "createdAt", "updatedAt"
    ) VALUES (?, ?, ?, 1, ?, ?)`,
  )
    .bind(userId, userId, email, NOW, NOW)
    .run();
}

async function insertTenant(tenantId: string): Promise<void> {
  await env.DB.prepare(
    `INSERT INTO tenants (
      tenant_id, status, shop_name, default_locale, default_currency, created_at, updated_at
    ) VALUES (?, 'active', ?, 'sv-SE', 'SEK', ?, ?)`,
  )
    .bind(tenantId, tenantId, NOW, NOW)
    .run();
}

describe("Better Auth and live authorization foundation", () => {
  it("matches the schema generated by the pinned Better Auth configuration", async () => {
    const auth = createAuth(env);
    const migrations = await getMigrations(auth.options);

    expect(migrations.toBeCreated).toEqual([]);
    expect(migrations.toBeAdded).toEqual([]);
    expect(auth.options.verification?.storeIdentifier).toBe("hashed");
  });

  it("installs auth and authorization tables", async () => {
    const result = await env.DB.prepare(
      `SELECT name FROM sqlite_master
       WHERE type = 'table'
         AND name IN (
           'user', 'session', 'account', 'verification', 'rateLimit',
           'identity_access', 'tenant_memberships', 'print_memberships'
         )
       ORDER BY name`,
    ).all<{ name: string }>();

    expect(result.results.map((row) => row.name)).toEqual([
      "account",
      "identity_access",
      "print_memberships",
      "rateLimit",
      "session",
      "tenant_memberships",
      "user",
      "verification",
    ]);
  });

  it("keeps account kind explicit and live", async () => {
    await insertUser("user-platform", "platform@example.test");
    await env.DB.prepare(
      `INSERT INTO identity_access (
        user_id, account_type, status, created_at, updated_at
      ) VALUES (?, 'platform_admin', 'active', ?, ?)`,
    )
      .bind("user-platform", NOW, NOW)
      .run();

    await expect(
      env.DB.prepare(
        `INSERT INTO identity_access (
          user_id, account_type, status, created_at, updated_at
        ) VALUES (?, 'print_operator', 'active', ?, ?)`,
      )
        .bind("user-platform", NOW, NOW)
        .run(),
    ).rejects.toThrow();

    const access = await env.DB.prepare(
      "SELECT account_type, status FROM identity_access WHERE user_id = ?",
    )
      .bind("user-platform")
      .first<{ account_type: string; status: string }>();

    expect(access).toEqual({ account_type: "platform_admin", status: "active" });
  });

  it("blocks tenant membership re-homing and duplicate roles", async () => {
    await insertTenant("tenant-auth-a");
    await insertTenant("tenant-auth-b");
    await insertUser("user-admin", "admin@example.test");

    const insertMembership = () =>
      env.DB.prepare(
        `INSERT INTO tenant_memberships (
          membership_id, tenant_id, user_id, role, status, created_at, updated_at
        ) VALUES (?, ?, ?, 'admin', 'active', ?, ?)`,
      )
        .bind("membership-admin", "tenant-auth-a", "user-admin", NOW, NOW)
        .run();

    await insertMembership();
    await expect(insertMembership()).rejects.toThrow();
    await expect(
      env.DB.prepare(
        `UPDATE tenant_memberships
         SET tenant_id = ?, updated_at = ?
         WHERE membership_id = ?`,
      )
        .bind("tenant-auth-b", NOW + 1, "membership-admin")
        .run(),
    ).rejects.toThrow("tenant_id is immutable");
  });

  it("allows explicit multi-tenant print assignments without tenant mutation", async () => {
    await insertTenant("tenant-print-a");
    await insertTenant("tenant-print-b");
    await insertUser("user-print", "print@example.test");

    await env.DB.batch([
      env.DB.prepare(
        `INSERT INTO print_memberships (
          membership_id, tenant_id, user_id, status, created_at, updated_at
        ) VALUES (?, ?, ?, 'active', ?, ?)`,
      ).bind("print-a", "tenant-print-a", "user-print", NOW, NOW),
      env.DB.prepare(
        `INSERT INTO print_memberships (
          membership_id, tenant_id, user_id, status, created_at, updated_at
        ) VALUES (?, ?, ?, 'active', ?, ?)`,
      ).bind("print-b", "tenant-print-b", "user-print", NOW, NOW),
    ]);

    const result = await env.DB.prepare(
      `SELECT tenant_id FROM print_memberships
       WHERE user_id = ? AND status = 'active'
       ORDER BY tenant_id`,
    )
      .bind("user-print")
      .all<{ tenant_id: string }>();

    expect(result.results.map((row) => row.tenant_id)).toEqual([
      "tenant-print-a",
      "tenant-print-b",
    ]);
  });
});
